# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Qisuk.ShortCutTool
PackageVersion: 1.1.0
InstallerType: inno
Scope: user
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
ProductCode: '{681BDEBB-6E4C-451C-A509-91C4D9F71A02}_is1'
AppsAndFeaturesEntries:
- DisplayName: ShortCut Tool
  Publisher: Qisuk
  ProductCode: '{681BDEBB-6E4C-451C-A509-91C4D9F71A02}_is1'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Qisuk/ShortCutTool/releases/download/v1.1.0/ShortCutTool-1.1.0-win-x64-setup.exe
  InstallerSha256: 6DB0AE1071222C25970E33496F1F90413DBA3328808CCB1FE34A355C01C2490B
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-10-08
